In [0]:
from databricks.sdk import WorkspaceClient
from pathlib import Path

wheel = Path("/tmp/drzavni_posao-0.1.0-py3-none-any.whl")
with WorkspaceClient().workspace.download(
    "/Users/luka.erceg@databricks.com/drzavni_posao/drzavni_posao-0.1.0-py3-none-any.whl"
) as source:
    wheel.write_bytes(source.read())

In [0]:
%pip install --force-reinstall --no-deps /tmp/drzavni_posao-0.1.0-py3-none-any.whl

Looking in indexes: [REDACTED]
Processing /tmp/drzavni_posao-0.1.0-py3-none-any.whl
Installing collected packages: drzavni-posao
Successfully installed drzavni-posao-0.1.0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
%pip install --force-reinstall --no-deps "https://github.com/mlflow/mlflow/archive/e07bf239b9dcf95e23fce5e59dff091df17669bc.zip"

Looking in indexes: [REDACTED]
Collecting https://github.com/mlflow/mlflow/archive/e07bf239b9dcf95e23fce5e59dff091df17669bc.zip
  Downloading https://github.com/mlflow/mlflow/archive/e07bf239b9dcf95e23fce5e59dff091df17669bc.zip
     - 297.4 MB 10.3 MB/s 0:00:15
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mlflow
  Building wheel for mlflow (pyproject.toml): started
  Building wheel for mlflow (pyproject.toml): finished with status 'done'
  Created wheel for mlflow: filename=mlflow-3.15.2.dev0-py3-none-any.whl size=3648511 sha256=d3b5b8b37bcdfeb7f708462ca6f8a65f648906ea1c5d4d9173051a0f5d93f063
  Stored in directory: /tmp/pip-ephem-wheel-cache-bv59_96h/wheels/cd/de/6a/6e363ff0eb82b49f06f5f2de21a16569afd221b664548c44ff
Successfully built mlflow
Installing collected packages: mlflow
Successfully installed mlflow-3.15.2.dev0
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
%pip install -U "bitsandbytes>=0.46.1"

Looking in indexes: [REDACTED]
Collecting bitsandbytes>=0.46.1
  Downloading http://node.host.local:8184/pypi/v1/packages/bitsandbytes/0.50.2/bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting torch<3,>=2.4 (from bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/torch/2.13.0/torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (38 kB)
Requirement already satisfied: numpy>=1.17 in /databricks/python/lib/python3.12/site-packages (from bitsandbytes>=0.46.1) (2.3.4)
Requirement already satisfied: packaging>=20.9 in /databricks/python/lib/python3.12/site-packages (from bitsandbytes>=0.46.1) (25.0)
Requirement already satisfied: filelock in /databricks/python/lib/python3.12/site-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /databricks/python/lib/python3.12/site-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (4.15.0)
Requirement already satisfied: setuptools>=77.0.3 in /databricks/python/lib/python3.12/site-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (80.9.0)
Collecting sympy>=1.13.3 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/sympy/1.14.0/sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/networkx/3.6.1/networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /databricks/python/lib/python3.12/site-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /databricks/python/lib/python3.12/site-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (2025.9.0)
Collecting cuda-toolkit==13.0.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/cuda-toolkit/13.0.3.0/cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/cuda-bindings/13.3.1/cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cudnn-cu13/9.20.0.48/nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cusparselt-cu13/0.8.1/nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nccl-cu13/2.29.7/nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nvshmem-cu13/3.4.5/nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton==3.7.1 (from torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/triton/3.7.1/triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cublas==13.1.1.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cublas/13.1.1.3/nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cuda-nvrtc/13.0.88/nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cuda-runtime/13.0.96/nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cufft/12.0.0.61/nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink<14,>=13.0.88 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nvjitlink/13.3.33/nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cufile/1.15.1.6/nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cuda-cupti/13.0.85/nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-curand/10.4.0.35/nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cusolver/12.0.4.66/nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cusparse/12.6.3.3/nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nvtx/13.0.85/nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting cuda-pathfinder>=1.4.2 (from cuda-bindings<14,>=13.0.3->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/cuda-pathfinder/1.7.0/cuda_pathfinder-1.7.0-py3-none-any.whl.metadata (1.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch<3,>=2.4->bitsandbytes>=0.46.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/mpmath/1.3.0/mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python/lib/python3.12/site-packages (from jinja2->torch<3,>=2.4->bitsandbytes>=0.46.1) (3.0.2)
Downloading http://node.host.local:8184/pypi/v1/packages/bitsandbytes/0.50.2/bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 113.8 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/torch/2.13.0/torch-2.13.0-cp312-cp312-manylinux_2_28_x86_64.whl (526.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 136.7 MB/s  0:00:02
Downloading http://node.host.local:8184/pypi/v1/packages/cuda-toolkit/13.0.3.0/cuda_toolkit-13.0.3.0-py2.py3-none-any.whl (2.5 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cudnn-cu13/9.20.0.48/nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl (366.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 163.2 MB/s  0:00:01
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cusparselt-cu13/0.8.1/nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 139.6 MB/s  0:00:01
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nccl-cu13/2.29.7/nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl (206.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 133.5 MB/s  0:00:01
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nvshmem-cu13/3.4.5/nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 138.8 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/triton/3.7.1/triton-3.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (197.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 142.1 MB/s  0:00:01
Downloading http://node.host.local:8184/pypi/v1/packages/cuda-bindings/13.3.1/cuda_bindings-13.3.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 122.9 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cublas/13.1.1.3/nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 128.8 MB/s  0:00:02
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cuda-cupti/13.0.85/nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 156.0 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cuda-nvrtc/13.0.88/nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 162.5 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cuda-runtime/13.0.96/nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 137.3 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cufft/12.0.0.61/nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 168.3 MB/s  0:00:01
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cufile/1.15.1.6/nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 132.4 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-curand/10.4.0.35/nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 166.7 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cusolver/12.0.4.66/nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 173.4 MB/s  0:00:01
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-cusparse/12.6.3.3/nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 177.6 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nvjitlink/13.3.33/nvidia_nvjitlink-13.3.33-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (40.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 174.8 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/nvidia-nvtx/13.0.85/nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/cuda-pathfinder/1.7.0/cuda_pathfinder-1.7.0-py3-none-any.whl (63 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/networkx/3.6.1/networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 156.5 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/sympy/1.14.0/sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 165.1 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/mpmath/1.3.0/mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 66.1 MB/s  0:00:00
Installing collected packages: nvidia-cusparselt-cu13, mpmath, cuda-toolkit, triton, sympy, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, networkx, cuda-pathfinder, nvidia-cusparse, nvidia-cufft, nvidia-cublas, cuda-bindings, nvidia-cusolver, nvidia-cudnn-cu13, torch, bitsandbytes
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24/24 [bitsandbytes]
Successfully installed bitsandbytes-0.50.2 cuda-bindings-13.3.1 cuda-pathfinder-1.7.0 cuda-toolkit-13.0.3.0 mpmath-1.3.0 networkx-3.6.1 nvidia-cublas-13.1.1.3 nvidia-cuda-cupti-13.0.85 nvidia-cuda-nvrtc-13.0.88 nvidia-cuda-runtime-13.0.96 nvidia-cudnn-cu13-9.20.0.48 nvidia-cufft-12.0.0.61 nvidia-cufile-1.15.1.6 nvidia-curand-10.4.0.35 nvidia-cusolver-12.0.4.66 nvidia-cusparse-12.6.3.3 nvidia-cusparselt-cu13-0.8.1 nvidia-nccl-cu13-2.29.7 nvidia-nvjitlink-13.3.33 nvidia-nvshmem-cu13-3.4.5 nvidia-nvtx-13.0.85 sympy-1.14.0 torch-2.13.0 triton-3.7.1
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
%pip install -U "transformers==5.8.1" "trl==1.10.0"

Looking in indexes: [REDACTED]
Collecting transformers==5.8.1
  Downloading http://node.host.local:8184/pypi/v1/packages/transformers/5.8.1/transformers-5.8.1-py3-none-any.whl.metadata (33 kB)
Collecting trl==1.10.0
  Downloading http://node.host.local:8184/pypi/v1/packages/trl/1.10.0/trl-1.10.0-py3-none-any.whl.metadata (12 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/huggingface-hub/1.28.0/huggingface_hub-1.28.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.17 in /databricks/python/lib/python3.12/site-packages (from transformers==5.8.1) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /databricks/python/lib/python3.12/site-packages (from transformers==5.8.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /databricks/python/lib/python3.12/site-packages (from transformers==5.8.1) (6.0.3)
Collecting regex>=2025.10.22 (from transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/regex/2026.7.19/regex-2026.7.19-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/tokenizers/0.22.2/tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/typer/0.27.1/typer-0.27.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.4.3 (from transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/safetensors/0.8.0/safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in /databricks/python/lib/python3.12/site-packages (from transformers==5.8.1) (4.67.1)
Collecting accelerate>=1.4.0 (from trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/accelerate/1.14.0/accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Collecting datasets>=4.7.0 (from trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/datasets/5.0.1/datasets-5.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /databricks/python/lib/python3.12/site-packages (from trl==1.10.0) (3.1.6)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/click/8.5.0/click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in /databricks/python/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /databricks/python/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (2025.9.0)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/hf-xet/1.6.0/hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/httpx/0.28.1/httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in /databricks/python/lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (4.15.0)
Requirement already satisfied: anyio in /databricks/python/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (4.10.0)
Requirement already satisfied: certifi in /databricks/python/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (2025.11.12)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/httpcore/1.0.9/httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /databricks/python/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (3.11)
Requirement already satisfied: h11>=0.16 in /databricks/python/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (0.16.0)
Requirement already satisfied: psutil in /databricks/python/lib/python3.12/site-packages (from accelerate>=1.4.0->trl==1.10.0) (7.0.0)
Requirement already satisfied: torch>=2.0.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from accelerate>=1.4.0->trl==1.10.0) (2.13.0)
Requirement already satisfied: pyarrow>=21.0.0 in /databricks/python/lib/python3.12/site-packages (from datasets>=4.7.0->trl==1.10.0) (21.0.0)
Collecting dill<0.4.2,>=0.3.0 (from datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/dill/0.4.1/dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /databricks/python/lib/python3.12/site-packages (from datasets>=4.7.0->trl==1.10.0) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /databricks/python/lib/python3.12/site-packages (from datasets>=4.7.0->trl==1.10.0) (2.32.5)
Collecting xxhash (from datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/xxhash/4.0.1/xxhash-4.0.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting multiprocess<0.70.20 (from datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/multiprocess/0.70.19/multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/aiohttp/3.14.3/aiohttp-3.14.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/aiohappyeyeballs/2.7.1/aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/aiosignal/1.4.0/aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/attrs/26.1.0/attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/frozenlist/1.8.0/frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/multidict/6.7.1/multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/propcache/0.5.2/propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets>=4.7.0->trl==1.10.0)
  Downloading http://node.host.local:8184/pypi/v1/packages/yarl/1.24.5/yarl-1.24.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (103 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /databricks/python/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.7.0->trl==1.10.0) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=4.7.0->trl==1.10.0) (2.5.0)
Requirement already satisfied: setuptools>=77.0.3 in /databricks/python/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (3.6.1)
Requirement already satisfied: cuda-toolkit==13.0.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (1.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl==1.10.0) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /databricks/python/lib/python3.12/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.8.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python/lib/python3.12/site-packages (from jinja2->trl==1.10.0) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /databricks/python/lib/python3.12/site-packages (from pandas->datasets>=4.7.0->trl==1.10.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /databricks/python/lib/python3.12/site-packages (from pandas->datasets>=4.7.0->trl==1.10.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /databricks/python/lib/python3.12/site-packages (from pandas->datasets>=4.7.0->trl==1.10.0) (2026.2)
Requirement already satisfied: six>=1.5 in /databricks/python/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl==1.10.0) (1.17.0)
Collecting shellingham>=1.3.0 (from typer->transformers==5.8.1)
  Downloading http://node.host.local:8184/pypi/v1/packages/shellingham/1.5.4/shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=13.8.0 in /databricks/python/lib/python3.12/site-packages (from typer->transformers==5.8.1) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /databricks/python/lib/python3.12/site-packages (from typer->transformers==5.8.1) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /databricks/python/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers==5.8.1) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /databricks/python/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers==5.8.1) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /databricks/python/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers==5.8.1) (0.1.2)
Downloading http://node.host.local:8184/pypi/v1/packages/transformers/5.8.1/transformers-5.8.1-py3-none-any.whl (10.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 177.4 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/trl/1.10.0/trl-1.10.0-py3-none-any.whl (925 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 925.8/925.8 kB 113.4 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/huggingface-hub/1.28.0/huggingface_hub-1.28.0-py3-none-any.whl (793 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 793.2/793.2 kB 102.3 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/click/8.5.0/click-8.5.0-py3-none-any.whl (125 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/hf-xet/1.6.0/hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 172.9 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/httpx/0.28.1/httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/httpcore/1.0.9/httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/tokenizers/0.22.2/tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 174.2 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/accelerate/1.14.0/accelerate-1.14.0-py3-none-any.whl (389 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/datasets/5.0.1/datasets-5.0.1-py3-none-any.whl (559 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 71.1 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/dill/0.4.1/dill-0.4.1-py3-none-any.whl (120 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/multiprocess/0.70.19/multiprocess-0.70.19-py312-none-any.whl (150 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/aiohttp/3.14.3/aiohttp-3.14.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 163.0 MB/s  0:00:00
Downloading http://node.host.local:8184/pypi/v1/packages/multidict/6.7.1/multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/yarl/1.24.5/yarl-1.24.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (109 kB)
Downloading http://node.host.local:8184/pypi/v1/packages/aiohappyeyeballs/2.7.1/aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)

In [0]:
%pip install -U "peft==0.19.1"

Looking in indexes: [REDACTED]
Collecting peft==0.19.1
  Downloading http://node.host.local:8184/pypi/v1/packages/peft/0.19.1/peft-0.19.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /databricks/python/lib/python3.12/site-packages (from peft==0.19.1) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /databricks/python/lib/python3.12/site-packages (from peft==0.19.1) (25.0)
Requirement already satisfied: psutil in /databricks/python/lib/python3.12/site-packages (from peft==0.19.1) (7.0.0)
Requirement already satisfied: pyyaml in /databricks/python/lib/python3.12/site-packages (from peft==0.19.1) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from peft==0.19.1) (2.13.0)
Requirement already satisfied: transformers in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from peft==0.19.1) (5.8.1)
Requirement already satisfied: tqdm in /databricks/python/lib/python3.12/site-packages (from peft==0.19.1) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from peft==0.19.1) (1.14.0)
Requirement already satisfied: safetensors in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from peft==0.19.1) (0.8.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from peft==0.19.1) (1.28.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft==0.19.1) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /databricks/python/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft==0.19.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /databricks/python/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft==0.19.1) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft==0.19.1) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft==0.19.1) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /databricks/python/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft==0.19.1) (4.15.0)
Requirement already satisfied: anyio in /databricks/python/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft==0.19.1) (4.10.0)
Requirement already satisfied: certifi in /databricks/python/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft==0.19.1) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft==0.19.1) (1.0.9)
Requirement already satisfied: idna in /databricks/python/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft==0.19.1) (3.11)
Requirement already satisfied: h11>=0.16 in /databricks/python/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft==0.19.1) (0.16.0)
Requirement already satisfied: setuptools>=77.0.3 in /databricks/python/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (3.6.1)
Requirement already satisfied: jinja2 in /databricks/python/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from torch>=1.13.0->peft==0.19.1) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=1.13.0->peft==0.19.1) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch>=1.13.0->peft==0.19.1) (1.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.13.0->peft==0.19.1) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /databricks/python/lib/python3.12/site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft==0.19.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python/lib/python3.12/site-packages (from jinja2->torch>=1.13.0->peft==0.19.1) (3.0.2)
Requirement already satisfied: regex>=2025.10.22 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from transformers->peft==0.19.1) (2026.7.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from transformers->peft==0.19.1) (0.22.2)
Requirement already satisfied: typer in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from transformers->peft==0.19.1) (0.27.1)
Requirement already satisfied: shellingham>=1.3.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages (from typer->transformers->peft==0.19.1) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /databricks/python/lib/python3.12/site-packages (from typer->transformers->peft==0.19.1) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /databricks/python/lib/python3.12/site-packages (from typer->transformers->peft==0.19.1) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /databricks/python/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers->peft==0.19.1) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /databricks/python/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers->peft==0.19.1) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /databricks/python/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers->peft==0.19.1) (0.1.2)
Downloading http://node.host.local:8184/pypi/v1/packages/peft/0.19.1/peft-0.19.1-py3-none-any.whl (680 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 680.7/680.7 kB 28.1 MB/s  0:00:00
Installing collected packages: peft
Successfully installed peft-0.19.1
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
dbutils.library.restartPython()

In [0]:
# Attach this notebook to Serverless GPU, 1xH100, AI v5 before running.
import os
import sys

os.environ["TQDM_DISABLE"] = "1"
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
os.environ["MLFLOW_ENABLE_ARTIFACTS_PROGRESS_BAR"] = "false"

import tqdm.auto
import tqdm.std

tqdm.auto.tqdm = tqdm.std.tqdm
tqdm.auto.trange = tqdm.std.trange

import logging
import math
from pathlib import Path
from statistics import fmean, median
from tempfile import mkdtemp

from drzavni_posao import MediaStore, MlflowTracker, Stage
from drzavni_posao.constants import ANONYMOUS_LABEL
from drzavni_posao.generation.dataset import (
    SFTDatasetBuilder,
    TranscriptQualityError,
    assign_folds,
    build_pair,
    select_splits,
)
from drzavni_posao.generation.inference import generate_episode

import mlflow
import torch
import transformers
import trl
import peft
from mlflow.tracking import MlflowClient
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    Qwen3_5ForConditionalGeneration,
    TrainerCallback,
    set_seed,
)
from trl import SFTConfig, SFTTrainer



logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
    force=True,
)
logging.getLogger("py4j").setLevel(logging.WARNING)
logging.getLogger("mlflow.system_metrics").setLevel(logging.WARNING)

SOURCE_EXPERIMENT_NAME = "/Users/luka.erceg@databricks.com/drzavni_posao/transcription"
SOURCE_RUN_ID = "1c519fba673841fa9188addf9a720ae6"
PREMISE_EXPERIMENT_NAME = (
    "/Users/luka.erceg@databricks.com/drzavni_posao/premise-generation"
)
PREMISE_RUN_ID = "4eadb1cda666464c90b6b01d71dbf574"
TRAINING_EXPERIMENT_NAME = (
    "/Users/luka.erceg@databricks.com/drzavni_posao/screenplay-qlora"
)
WORKSPACE_ROOT = Path("/Workspace/Users/luka.erceg@databricks.com/drzavni_posao")

MODEL_KEY = "qwen38"  # Choose "qwen3", "qwen38", or "zora".
MODEL_NAMES = {
    "qwen3": "Qwen/Qwen3-8B",
    "qwen38": "Qwen/Qwen3.8-27B",
    "zora": "sovasoft/zora-v1.12",
}
if MODEL_KEY not in MODEL_NAMES:
    raise ValueError(f"Unknown model key {MODEL_KEY!r}; choose from {sorted(MODEL_NAMES)}")
MODEL_NAME = MODEL_NAMES[MODEL_KEY]
MODEL_CLASS = (
    Qwen3_5ForConditionalGeneration
    if MODEL_KEY == "qwen38"
    else AutoModelForCausalLM
)
LORA_TARGET_MODULES = (
    [
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "in_proj_qkv",
        "in_proj_z",
        "in_proj_b",
        "in_proj_a",
        "out_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ]
    if MODEL_KEY == "qwen38"
    else ["q_proj", "v_proj"]
)
RUN_NAME = f"{MODEL_KEY}-qlora-full-episode-v5-losses"
MAX_LENGTH = 8192
MAX_NEW_TOKENS = 2048
GENERATION_DO_SAMPLE = True
GENERATION_TEMPERATURE = 0.8
GENERATION_TOP_P = 0.95
GENERATION_TOP_K = 0
GENERATION_REPETITION_PENALTY = 1.15
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 8
LEARNING_RATE = 1e-4
TRAIN_EPOCHS = 2
WARMUP_RATIO = 0.05
MAX_GRAD_NORM = 0.3
SEED = 42

EXPECTED_TRANSFORMERS_VERSION = "5.8.1"
EXPECTED_TRL_VERSION = "1.10.0"
if transformers.__version__ != EXPECTED_TRANSFORMERS_VERSION:
    raise RuntimeError(
        f"Expected transformers {EXPECTED_TRANSFORMERS_VERSION}, "
        f"found {transformers.__version__}"
    )
if trl.__version__ != EXPECTED_TRL_VERSION:
    raise RuntimeError(f"Expected TRL {EXPECTED_TRL_VERSION}, found {trl.__version__}")

if not torch.cuda.is_available():
    raise RuntimeError("This notebook requires a GPU")
GPU_NAME = torch.cuda.get_device_name(0)
if "H100" not in GPU_NAME:
    raise RuntimeError(f"Expected an H100, found {GPU_NAME}")

set_seed(SEED)
print(
    {
        "gpu": GPU_NAME,
        "model_key": MODEL_KEY,
        "model_name": MODEL_NAME,
        "transformers": transformers.__version__,
        "trl": trl.__version__,
        "peft": peft.__version__,
    }
)

/local_disk0/.ephemeral_nfs/envs/pythonEnv-342f9a0b-1694-4cc2-98f9-6681a8f093a3/lib/python3.12/site-packages/torch/_vmap_internals.py:9: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  from torch.utils._pytree import _broadcast_to_and_flatten, tree_flatten, tree_unflatten

{'gpu': 'NVIDIA H100 80GB HBM3', 'model_key': 'qwen38', 'model_name': 'Qwen/Qwen3.8-27B', 'transformers': '5.8.1', 'trl': '1.10.0', 'peft': '0.19.1'}

In [0]:
from databricks.sdk import WorkspaceClient
from pathlib import Path

catalog_path = Path("/tmp/youtube_episodes.json")
with WorkspaceClient().workspace.download(
    "/Users/luka.erceg@databricks.com/drzavni_posao/data/youtube_episodes.json"
) as source:
    catalog_path.write_bytes(source.read())

In [0]:
source_tracker = MlflowTracker(SOURCE_EXPERIMENT_NAME)
states = source_tracker.episode_run_states(SOURCE_RUN_ID)

mlflow.set_experiment(PREMISE_EXPERIMENT_NAME)
traces = mlflow.search_traces(
    run_id=PREMISE_RUN_ID,
    max_results=1000,
    return_type="list",
)

premises = {}
empty_episode_keys = []
for trace in traces:
    if trace.info.tags.get("premise.complete") != "true":
        continue

    episode_key = trace.info.tags.get("episode_key")
    outputs = trace.data.spans[0].outputs if trace.data.spans else None
    premise = ((outputs or {}).get("premise") or "").strip()
    if not episode_key or not premise:
        if episode_key:
            empty_episode_keys.append(episode_key)
        continue
    if episode_key in premises:
        raise ValueError(f"Multiple valid premises found for episode {episode_key!r}")
    premises[episode_key] = premise

media = MediaStore(
    audio_dir=None,
    run_dir=Path("/tmp/screenplay-qlora"),
    catalog_path=catalog_path
)
source_episodes = [
    episode
    for episode in media.episodes()
    if episode.key in states
    and Stage.CHARACTER_ASSIGNER in states[episode.key].completed_stages
]
folds = assign_folds(source_episodes)
splits = select_splits(folds, test_fold=0, validation_fold=1)

rows = []
quality_exclusions = {}
anonymous_segments_removed = 0
for episode in source_episodes:
    premise = premises.get(episode.key)
    if premise is None:
        continue

    episode.transcript = source_tracker.stage_transcript(
        states[episode.key].run_id,
        Stage.CHARACTER_ASSIGNER,
    )
    anonymous_segments_removed += sum(
        segment.get("speaker") == ANONYMOUS_LABEL
        for segment in episode.transcript.segments
    )
    try:
        pair = build_pair(episode, premise)
    except TranscriptQualityError as error:
        quality_exclusions[episode.key] = error.reasons
        continue
    rows.append({**pair, "split": splits[episode.key]})

if not rows:
    raise ValueError("No valid premise/dialogue pairs found")

print(f"valid pairs: {len(rows)}")
print(f"empty premises filtered: {len(empty_episode_keys)}")
print(f"quality exclusions: {len(quality_exclusions)}")
print(f"anonymous segments removed: {anonymous_segments_removed}")
if quality_exclusions:
    print(quality_exclusions)
print(
    "splits:",
    {
        split: sum(row["split"] == split for row in rows)
        for split in ("train", "validation", "test")
    },
)

If you are using MLflow Tracing, you can migrate your traces to Unity Catalog for unlimited storage, fine-grained access controls, and queryability from notebooks, SQL, and dashboards. Learn more: https://docs.databricks.com/aws/en/mlflow3/genai/tracing/migrate-traces-to-uc

2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 6
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 8
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:27 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 8
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 8
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:28 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 7
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 8
2026-08-27 04:14:29 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 9
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10
2026-08-27 04:14:30 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: storage-proxy.databricks.com. Connection pool size: 10

In [0]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

dataset_builder = SFTDatasetBuilder(
    tokenizer,
    max_length=MAX_LENGTH,
    enable_thinking=False,
)
split_rows, overlong_episode_keys = dataset_builder.prepare_rows(rows)
dataset = dataset_builder.build_dataset(split_rows)
training_rows = [
    row
    for split in ("train", "validation", "test")
    for row in split_rows[split]
]

print(dataset)
print(f"overlong episodes filtered: {overlong_episode_keys}")
print(
    "token range:",
    min(row["token_count"] for row in training_rows),
    max(row["token_count"] for row in training_rows),
)

2026-08-27 04:20:25 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/agent-harnesses "HTTP/1.1 200 OK"
2026-08-27 04:20:25 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

2026-08-27 04:20:25 - huggingface_hub.utils._http - WARNING - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-27 04:20:25 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json "HTTP/1.1 200 OK"
2026-08-27 04:20:25 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.8-27B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.8-27B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/vocab.json "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/vocab.json "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/merges.txt "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/merges.txt "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/merges.txt "HTTP/1.1 200 OK"
2026-08-27 04:20:26 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/tokenizer.json "HTTP/1.1 302 Found"
2026-08-27 04:20:27 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-08-27 04:20:27 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
2026-08-27 04:20:27 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/chat_template.jinja "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:27 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/chat_template.jinja "HTTP/1.1 200 OK"
2026-08-27 04:20:27 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/chat_template.jinja "HTTP/1.1 200 OK"
2026-08-27 04:20:28 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.8-27B "HTTP/1.1 200 OK"
DatasetDict({
    train: Dataset({
        features: ['prompt', 'completion', 'chat_template_kwargs'],
        num_rows: 548
    })
    validation: Dataset({
        features: ['prompt', 'completion', 'chat_template_kwargs'],
        num_rows: 70
    })
    test: Dataset({
        features: ['prompt', 'completion', 'chat_template_kwargs'],
        num_rows: 70
    })
})
overlong episodes filtered: ['283', 'Novogodišnji specijal (2014-12-31)', 'Novogodišnji specijal (2015-12-31)']
token range: 1352 6369

In [0]:
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)
model = MODEL_CLASS.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    torch_dtype=torch.bfloat16,
    device_map={"": 0},
)
model.config.use_cache = False
if hasattr(model.config, "text_config"):
    model.config.text_config.use_cache = False

available_module_names = {
    name.rsplit(".", 1)[-1] for name, _ in model.named_modules()
}
missing_target_modules = sorted(set(LORA_TARGET_MODULES) - available_module_names)
if missing_target_modules:
    raise RuntimeError(f"Missing LoRA target modules: {missing_target_modules}")

model = prepare_model_for_kbit_training(
    model,
    use_gradient_checkpointing=True,
)
model = get_peft_model(
    model,
    LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        target_modules=LORA_TARGET_MODULES,
        bias="none",
        task_type="CAUSAL_LM",
    ),
)
if MODEL_KEY == "qwen38":
    trainable_vision_parameters = [
        name
        for name, parameter in model.named_parameters()
        if parameter.requires_grad and ("vision" in name or "visual" in name)
    ]
    if trainable_vision_parameters:
        raise RuntimeError(
            f"Vision parameters unexpectedly trainable: {trainable_vision_parameters[:5]}"
        )
model.print_trainable_parameters()
print(
    "GPU memory after model preparation (GiB):",
    round(torch.cuda.max_memory_allocated() / 1024**3, 2),
)

OUTPUT_DIR = mkdtemp(prefix=f"{MODEL_KEY}-qlora-")
training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    max_length=MAX_LENGTH,
    completion_only_loss=True,
    packing=False,
    num_train_epochs=TRAIN_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=LEARNING_RATE,
    lr_scheduler_type="cosine",
    warmup_ratio=WARMUP_RATIO,
    weight_decay=0.01,
    max_grad_norm=MAX_GRAD_NORM,
    optim="paged_adamw_8bit",
    bf16=True,
    tf32=True,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    eval_strategy="epoch",
    eval_on_start=True,
    save_strategy="epoch",
    save_total_limit=1,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    logging_steps=1,
    report_to="mlflow",
    run_name=RUN_NAME,
    seed=SEED,
    data_seed=SEED,
)
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    processing_class=tokenizer,
)


def score_episode_losses(model, data_collator, processed_dataset, keyed_rows, split):
    if len(processed_dataset) != len(keyed_rows):
        raise ValueError(
            f"{split} dataset has {len(processed_dataset)} examples but "
            f"{len(keyed_rows)} keyed rows"
        )

    records = []
    was_training = model.training
    model.eval()
    try:
        for row, example in zip(keyed_rows, processed_dataset, strict=True):
            episode_key = row["episode_key"]
            if row["split"] != split:
                raise ValueError(
                    f"Episode {episode_key!r} belongs to {row['split']!r}, not {split!r}"
                )

            batch = data_collator([example])
            labels = batch.get("labels")
            if labels is None:
                raise RuntimeError(f"Episode {episode_key!r} has no labels")
            supervised_tokens = int(labels[..., 1:].ne(-100).sum().item())
            if supervised_tokens == 0:
                raise RuntimeError(f"Episode {episode_key!r} has no supervised tokens")

            batch = {
                key: value.to(model.device)
                for key, value in batch.items()
                if torch.is_tensor(value)
            }
            with (
                torch.inference_mode(),
                torch.autocast("cuda", dtype=torch.bfloat16),
            ):
                output = model(**batch)
            loss = float(output.loss.detach().cpu())
            if not math.isfinite(loss):
                raise RuntimeError(f"Episode {episode_key!r} produced loss {loss}")
            records.append(
                {
                    "episode_key": episode_key,
                    "split": split,
                    "loss": loss,
                    "supervised_tokens": supervised_tokens,
                }
            )
            del output, batch
    finally:
        model.train(was_training)

    return records


class EpisodeLossCallback(TrainerCallback):
    def __init__(self, trainer, split_rows):
        self.data_collator = trainer.data_collator
        self.datasets = {
            "train": trainer.train_dataset,
            "validation": trainer.eval_dataset,
        }
        self.rows = {
            split: split_rows[split]
            for split in ("train", "validation")
        }
        for split in self.datasets:
            if len(self.datasets[split]) != len(self.rows[split]):
                raise ValueError(
                    f"{split} dataset has {len(self.datasets[split])} examples but "
                    f"{len(self.rows[split])} keyed rows"
                )

    def on_epoch_end(self, args, state, control, model=None, **kwargs):
        if not state.is_world_process_zero:
            return control
        if model is None or state.epoch is None:
            raise RuntimeError("Epoch-end episode scoring requires a model and epoch")

        epoch = int(round(state.epoch))
        records = []
        metrics = {}
        for split in ("train", "validation"):
            split_records = score_episode_losses(
                model,
                self.data_collator,
                self.datasets[split],
                self.rows[split],
                split,
            )
            records.extend(split_records)
            losses = [record["loss"] for record in split_records]
            metrics[f"episode_loss.{split}.mean"] = fmean(losses)
            metrics[f"episode_loss.{split}.median"] = median(losses)

        mlflow.log_dict(
            {
                "epoch": epoch,
                "global_step": state.global_step,
                "records": records,
            },
            f"episode-losses/epoch-{epoch:03d}.json",
        )
        mlflow.log_metrics(metrics, step=state.global_step)
        print(f"epoch {epoch} episode losses:", metrics)
        return control


first_training_row = split_rows["train"][0]
expected_prompt_ids = tokenizer.apply_chat_template(
    first_training_row["prompt"],
    tokenize=True,
    add_generation_prompt=True,
    enable_thinking=False,
    return_dict=True,
)["input_ids"]
expected_full_ids = tokenizer.apply_chat_template(
    first_training_row["prompt"] + first_training_row["completion"],
    tokenize=True,
    add_generation_prompt=False,
    enable_thinking=False,
    return_dict=True,
)["input_ids"]
if expected_full_ids[: len(expected_prompt_ids)] != expected_prompt_ids:
    raise RuntimeError("Tokenizer prompt mismatch before completion")

first_training_example = trainer.train_dataset[0]
input_ids = first_training_example["input_ids"]
labels = first_training_example.get("labels")
if labels is None:
    raise RuntimeError("TRL did not create completion-only labels")
masked_prompt_tokens = sum(label == -100 for label in labels)
supervised_completion_tokens = len(labels) - masked_prompt_tokens
if input_ids != expected_full_ids:
    raise RuntimeError("TRL tokenization differs from the expected chat template")
if masked_prompt_tokens != len(expected_prompt_ids):
    raise RuntimeError(
        f"Expected {len(expected_prompt_ids)} masked prompt tokens, "
        f"found {masked_prompt_tokens}"
    )
if labels[:masked_prompt_tokens] != [-100] * masked_prompt_tokens:
    raise RuntimeError("Prompt labels are not fully masked")
if labels[masked_prompt_tokens:] != input_ids[masked_prompt_tokens:]:
    raise RuntimeError("Completion labels do not match completion tokens")
print(
    "completion-only labels:",
    {
        "prompt_tokens": masked_prompt_tokens,
        "completion_tokens": supervised_completion_tokens,
    },
)

scoring_smoke_test = score_episode_losses(
    model,
    trainer.data_collator,
    trainer.train_dataset.select([0]),
    split_rows["train"][:1],
    "train",
)
if scoring_smoke_test[0]["supervised_tokens"] != supervised_completion_tokens:
    raise RuntimeError(
        "Episode-loss scorer counted a different number of supervised tokens"
    )
print("episode-loss scoring smoke test:", scoring_smoke_test[0])
trainer.add_callback(EpisodeLossCallback(trainer, split_rows))

2026-08-27 04:20:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json "HTTP/1.1 200 OK"
2026-08-27 04:20:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-08-27 04:20:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json "HTTP/1.1 200 OK"
2026-08-27 04:20:32 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-08-27 04:20:32 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:20:32 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-08-27 04:20:32 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-08-27 04:20:32 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.8-27B/revision/main "HTTP/1.1 200 OK"
2026-08-27 04:20:33 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.8-27B/tree/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0?recursive=true&expand=false "HTTP/1.1 200 OK"

[transformers] The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

2026-08-27 04:21:25 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 04:21:25 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/generation_config.json "HTTP/1.1 200 OK"
2026-08-27 04:21:25 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/generation_config.json "HTTP/1.1 200 OK"

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 58,363,904 || all params: 27,415,092,464 || trainable%: 0.2129
GPU memory after model preparation (GiB): 23.81
completion-only labels: {'prompt_tokens': 340, 'completion_tokens': 1624}

In [0]:
mlflow.set_experiment(TRAINING_EXPERIMENT_NAME)
with mlflow.start_run(run_name=RUN_NAME) as run:
    TRAINING_RUN_ID = run.info.run_id
    mlflow.set_tags(
        {
            "model_key": MODEL_KEY,
            "model_name": MODEL_NAME,
            "training_method": "qlora",
            "dataset_paradigm": "full_episode",
            "source_run_id": SOURCE_RUN_ID,
            "premise_run_id": PREMISE_RUN_ID,
        }
    )
    mlflow.log_params(
        {
            "model_key": MODEL_KEY,
            "max_length": MAX_LENGTH,
            "lora_r": LORA_R,
            "lora_alpha": LORA_ALPHA,
            "lora_dropout": LORA_DROPOUT,
            "lora_target_modules": ",".join(LORA_TARGET_MODULES),
            "batch_size": BATCH_SIZE,
            "gradient_accumulation_steps": GRADIENT_ACCUMULATION_STEPS,
            "learning_rate": LEARNING_RATE,
            "epochs": TRAIN_EPOCHS,
            "warmup_ratio": WARMUP_RATIO,
            "max_grad_norm": MAX_GRAD_NORM,
            "transformers_version": transformers.__version__,
            "trl_version": trl.__version__,
            "peft_version": peft.__version__,
            "seed": SEED,
        }
    )
    mlflow.log_metrics(
        {
            "dataset.valid_pairs": len(rows),
            "dataset.empty_premises": len(empty_episode_keys),
            "dataset.quality_exclusions": len(quality_exclusions),
            "dataset.anonymous_segments_removed": anonymous_segments_removed,
            "dataset.overlong_examples": len(overlong_episode_keys),
            **{
                f"dataset.{split}_examples": len(items)
                for split, items in split_rows.items()
            },
        }
    )
    mlflow.log_dict(
        {
            "source_experiment_name": SOURCE_EXPERIMENT_NAME,
            "source_run_id": SOURCE_RUN_ID,
            "premise_experiment_name": PREMISE_EXPERIMENT_NAME,
            "premise_run_id": PREMISE_RUN_ID,
            "empty_episode_keys": empty_episode_keys,
            "quality_exclusions": quality_exclusions,
            "anonymous_segments_removed": anonymous_segments_removed,
            "overlong_episode_keys": overlong_episode_keys,
            "rows": [
                {
                    "episode_key": row["episode_key"],
                    "split": row["split"],
                    "premise": row["premise"],
                    "token_count": row["token_count"],
                }
                for row in training_rows
            ],
        },
        "dataset_manifest.json",
    )

    train_result = trainer.train()
    eval_metrics = trainer.evaluate()
    mlflow.log_metrics(
        {
            key: float(value)
            for key, value in eval_metrics.items()
            if isinstance(value, (int, float))
        }
    )

    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    mlflow.log_artifacts(OUTPUT_DIR, artifact_path="adapter")

print(f"training run: {TRAINING_RUN_ID}")
print(eval_metrics)

2026-08-27 04:21:39 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/telemetry/trl/SFTTrainer "HTTP/1.1 200 OK"

If you are using MLflow Tracing, you can migrate your traces to Unity Catalog for unlimited storage, fine-grained access controls, and queryability from notebooks, SQL, and dashboards. Learn more: https://docs.databricks.com/aws/en/mlflow3/genai/tracing/migrate-traces-to-uc
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 248046, 'bos_token_id': None, 'pad_token_id': 248044}.

2026-08-27 06:13:46 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 06:13:46 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json "HTTP/1.1 200 OK"
2026-08-27 08:03:04 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 08:03:04 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json "HTTP/1.1 200 OK"

2026-08-27 08:05:23 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.8-27B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-27 08:05:23 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.8-27B/1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0/config.json "HTTP/1.1 200 OK"
training run: 0dd0755b40e04beea2112bb7d7ea6baf
{'eval_loss': 2.7154290676116943, 'eval_entropy': 2.7359226669584, 'eval_num_tokens': 3245214.0, 'eval_mean_token_accuracy': 0.48162133055073875}

In [0]:
heldout = split_rows["test"][8]
model.gradient_checkpointing_disable()
model.config.use_cache = True
if hasattr(model.config, "text_config"):
    model.config.text_config.use_cache = True
model.eval()

comparison = {
    "episode_key": heldout["episode_key"],
    "premise": heldout["premise"],
    "base": generate_episode(
        model,
        tokenizer,
        heldout["premise"],
        adapter_enabled=False,
        seed=SEED,
        max_new_tokens=MAX_NEW_TOKENS,
        do_sample=GENERATION_DO_SAMPLE,
        temperature=GENERATION_TEMPERATURE,
        top_p=GENERATION_TOP_P,
        top_k=GENERATION_TOP_K,
        repetition_penalty=GENERATION_REPETITION_PENALTY,
    ),
    "qlora": generate_episode(
        model,
        tokenizer,
        heldout["premise"],
        adapter_enabled=True,
        seed=SEED,
        max_new_tokens=MAX_NEW_TOKENS,
        do_sample=GENERATION_DO_SAMPLE,
        temperature=GENERATION_TEMPERATURE,
        top_p=GENERATION_TOP_P,
        top_k=GENERATION_TOP_K,
        repetition_penalty=GENERATION_REPETITION_PENALTY,
    ),
}
MlflowClient().log_dict(
    TRAINING_RUN_ID,
    comparison,
    "heldout_comparison.json",
)
print(comparison)

{'episode_key': '76', 'premise': 'Posle novogodišnjeg slavlja, Boškić dolazi na posao mamuran i zatiče Čvarkova i Torbicu usred rasprave o tome da li je uopšte trebalo raditi tokom praznika. Njihovo negodovanje zbog omladine i savremenih navika prerasta u nostalgično prisećanje na „pristojno“ opijanje i nekadašnje običaje. Glavna tema epizode je apsurdna kancelarijska filozofija o alkoholu, radu i lekovima za mamurluk, uz sve neobičnije savete kolega.', 'base': '[Djordje Cvarkov] Vidi ga kako ulazi, hoda kao kakva pijana kokoška što je prvi put ugledala ogledalce. A mi smo tu, čistimo arhivu iz \'92. godine, čuvamo integritet državnog aparata. I on nam donese energiju božićnih jelki iz prodavnice nameštaja.\n\n[Dragan Torbica] Ne možeš da sporediš novo sa starim, brate. Kada bismo mi popili po čašu rakije na Badnji dan, niko nije trčao do farmaceutike po obloge od krompira. Mi smo sedeli, šutjeli i gledali u zid dok nam glava nije postajala prozirna kao staklo iz ove ladice. To je bio meditativni proces. Sada oni misle da je mamurluk bolest koju treba lečiti tabletama koje im miriše na plastiku i beda.\n\n[Boskic] Hvala vam... baš hvala. Samo sam želeo da pitam da li imam slobodan popodne jer me vrtelo već u autobusu 14, a kod kuće je majka spremila supe koju ću morati da preguram da bih izgubio miris dima i lošeg probave. Meni glava puca, nisam jadikullio, nisam plakao, jednostavno vidim dve svetišta kada pogledam u svetla na plafonu. Da li vi imate neki lek? Jer ja nemam nikakve krome. Nemam ni para za voće. Imam samo ovako prazan želudac i osećaj krivice prema računaru koji me gleda sa ekrana.\n\n[Djordje Cvarkov] Krivica? Kakva krivica? Ti si večerao u "Fruškoj" juče. Ja te video. Sirove riblje šnicle, tri vrste salate i tartaleta sa kajmakom. To nije hrana, to je bomba koja eksplodira u stomaku nakon četiri sata. A ti si u to dodao onaj gorki sok od dinje. Znaš šta je tu trik, Boskiću? Trik nije u tome koliko piješ, nego koliko malo jedeš. Ako jedeš, telo troši enzimsku snagu na varenje, a ne na neutralizaciju etanola. Biološka matematika je jednostavna: manje salate, veći ukus rakije.\n\n[Boskic] Dakle, ako ne jedem ništa sutra, prestaću da me boli?\n\n[Dragan Torbica] Ne, Brane. Ne moraš da gladuješ. Moraš da unosiš kalorije, ali one kalorične jedinice ne smeju da sadrže sapun ili luk. Uzgadi, zamislite našeg dedu. On bi posle kafane stigao kući, seo na stolicu i rekao: "Miša, staviti mi toplog rastvora soleviteta u kolonadu." Bez tableta. Bez cirkusa. Golemina tela sama rešava hemijsku jednadžbu. Ti sada hoćeš da ti neko ubrizga struju direktno u mozgu da bi ti prigušilo osmose. To je birokratizacija ljudskog tela. Previše papira u glavnom delu organizma.\n\n[Boskic] Moj otac kaže da treba da jedem sendviče sa sirutićem i pijem puno vode. Ali moja voda teče crveno kad je ispijam. Šta znači ta voda? Je li to znak da su organi počeli da se raspadaؤ?\n\n[Djordje Cvarkov] Crvena voda znači da si pretjerao sa tom tamnom đumbirskom limunadom koju si pio umesto vode. To nije urina, Boskiću. To je indikator kvaliteta tvojih izbora. Vrati se na ono primitivno. Voda. Obična, mineralna, iz slavine. Ona ne traži naplatu, ona ne ima ambicije. Ona samo prolazi kroz creva i nosi sa sobom toksine. Kao što arhiva čuva dokumente, tako i bubreg čuva tvoj dugu životnosti. A ti rušiš sistem.\n\n[Dragan Torbica] Ja imam jedan recept. Proveren. Kada bismo mi imali probleme posle gostovanja, išli bismo u park Pivara. Sedali na klupu. Ne govoreći ništa. Deset minuta šutanja. Telo shvati da nema publike i prestaje da reaguje dramatično. Ljudski organi volišu pažnju, zato i sami izazivaju simptome. Kad ih ignorišeš, oni se povuku u pozadinu i rade svoj posao. Ti pričaš o njima celog dana, pa oni misle da si im fanboy. Prestani da budeš zavisnik sopstvenog mučenja.\n\n[Boskic] Dakle, da sednem u hodniku deset minuta? I samo da dišem?\n\n[Djordje Cvarkov] Tačno. I ne doticati se kompjutora. Ekran pulsira, a tvoje nervi su trenutno najsličniji električnoj žici bez izolacije. Koža će se uskladiti sa frekvencijom monitora i dobićeš migrenu od piksela. Idemo mi dalje sa katalogizacijom zahteva za građevinske dozvole iz devedesetih. Ti sjedi, drži usta zatvorena i razmišljaj o prirodi vode. Voda je demokratska supstanca. Sve pije, nitko se ne žalī. Budi kao voda.\n\n[Boskic] Dobro... ali da li mogu da legnem pod stolom? Ima prostora između noge sto i radijatora. Tu je toplo. I mrkavo.\n\n[Dragan Torbica] Pod stolom je arhitektonski grešno mesto za čoveka koji pokušava da ostane vertikalni simbol društvene odgovornosti. Lezi u fotelju. Nasloni glavu o ramena. Zamisi da si korijen biljke. Korne šalja signale nadole, ti šalja gore. Ravnoteža. I slušaj, sutra ne nosi taj parfem za raspadajuće šećer. Dođi bosa, možda. Zemlja izvucе negativi iz stopala. Stare metode, Boskiću. Bez tableta. Bez panike. Sami ćemo se izvući, kao i svaki drugi državni službenik od pedeset godina.', 'qlora': "[Djordje Cvarkov] Predovi kraljice, hvala vam što ste došli da pomegnete sa nama. Dosta smo vas ove godine viđali. Hvala sto su se tolike muke podigali, starješine, svuda po gradu. Ne zna ono čime se nešto ne osjeće kako bi bilo nemoće bolje da nam visi preko klupi nemoći...\n[Dragan Torbica] Jel' je ovo posao? Da ne vidim još! To sam ja razumio da kad se dajete tačka sa nove 1996., ti sad dolaze na posao od rano na put pa gledamo kako će sve da ide jer tu nema nikakvog problema. Pa šta je mene briga što radi, radio on ili nije radio. Ma ništa me to ne zanima. Otkud mi žude naše mlade da im bude sve bolje nego meni, očevcu, majci. Žele se oni ali se ne vraćaju. Ima sanuka. Ti si bila žena sloboda na zoru, a sada ste, stani za milion dinara, bar je malo ruku da krojaći, milane po tom ide kod tebe.\n[Boskic] Čeka ljudi dragi moji, ajd' mi samo malo, ajd' pet minuta prepuste, probajte lako, ja sam pri završetku, pa onda možda idem da popijem kafu iznad u blagajnu, tamo stiže ovoz kakva dobra mala, ona kuca odlično, sjajna devojčica. Ajme, ako hoću, mogu zato da sednem, a predzvečer da ode, jel' tako, al' dobro, pa evo ga, da kažem mužikama, prebačajte. Što mislite? Nema šanse, večerao sam? U mojoj gradnji više nije bilo šansi, uglavnom se žuljim do nekih četiri. Tola je dva puta vodila psa, tamo baš je uza ulicu, u Užavu, k'o da pijem, onaj hajlajt koji uveliko prodaju. Pojedini ljudi imaju problema sa jetrom, ima neki lek, naftina, jedan salatinski prir, a to se sve kupuje, je li ja shvatam? Dobro je bilo u vreme kada sam bio dete, ali to nema više smisla za današnje vreme. Dečki, ajde fiih, ma znam ja, kažem da je najgora stvar, govorim jer nisam znao da ćete dolaziti ranije. To ne bi i dopao odmah kao poludio da vežu oko gola, cirkuski broj. Vidi koliko sam je onaj crveni, pa oti, dolazili gde treba, ne baš svi po jedna bočica, baš po jedno piće, jel'? Kad dođeš na jutru, šta misliš da izgledaš? Možda si ljut kad se osvetimo? Aj, već je sunce peče. Pa to nije točno jer postoji nekoliko varijanti kako da se spreči osetanje mamurka, molim vas, ali onaj narodni sastavlinar, onaj koji ne može da se odvozi za maslačkom, ima mnogo, kako kažete? Ne dobijački naš, dovoljno je poznato, ali on je najbolji.\n[Djordje Cvarkov] Jer puno više me boli glava od vas dvojice nego što mi bole od mamurluka. Ti jedno piće nisi mogao da popiješ? A drugo, svaki dan si ti ovde, negde da istrpiš ceo ovaj dnevnik.\n[Dragan Torbica] Ja pičem tvoju omiljenutrinu na tvom računu, jer znas da voliš, pa ti jednom popioš svih deset, jednu na pola. E, to je bio moj dan točke.\n[Boskic] Samo naručite mi u blagajnu do jutra, zamolim vas, toliko mi je pucao trbu, napunilo se. Trebam ja samo malo otići, prolit ćemo kafu.\n[Djordje Cvarkov] Kako tako mamećko? Ko igra, tako i gubi, Boško. Kakvi su bili naši proslavi? Oni su tebi ponekad pomogli. Ali mislim ti samo jedan piće. Je boga, normalno, da tebi nešto valja. Mi smo otkakad pokazali da je to pristojnost. Pristojno je opijeti kada se pije domača rakija koja se sli čuva godina-dvanaest. Moje strašno, kad god dođe rođendana, tražio je dvanaest sati, tri puno ruku koje mi je neke strane davali, a ja njemu davao. Sljedeće generacije su bile desetine liša marlovci. Baš ono što treba, sitno, fino, sipano, pa napolje, da popiju, da proguta. Znam. Nisi prestao, kažeš. Onaj Miho, da samo vadi u pet foliju. Ja nemam čist od netipičnih želaca, govoriš. Ma, tipični su. Mašine su one za otklanjanje. Drugo je golubnjak. Treći kolačić. Maksimalno šest metara dalje od stolice, možete, jer nije potrebno da nosi malu dozu. Tu je i drugi brendi za nakon toga. Onaj prvi, onaj manji da se na prst položi, kad maljaš da popiješ svega 50 mililitra, prekrijte papirnjakom, stavite da izvire kroz pola satra.\n[Dragan Torbica] Sa tim inženjerima, eh, oni ludo provode, pa ti i ne možeš da ih pridržiš. Jednom sam rekao sine, prodrinu, da tekte, jednog ga ujeli, čekao treći vikend, ali ja ne mogu, gotovi mi do grobova. A onda kad se budu toliko napuno, neće ništa mogu da uradim, skloni se. Tako, samo tu kao meču. Stavi kad sramota, a onda mu dišeš, čekaj zlatu minutu da ga ostaviš da udahne paru. Pa bukavno ukoliše se, drži je dok ono ne strah. Verujte, ja sam za taj period, kad ga nosimo unutra, jednu jednu luplja po vratu ga zatvara. I tako ga stavim da spava, nema ništa, ni kap vode umetanja, izvučen iako troše, nikakvih posledica, vojnički je, isto kao nešto u krvi, ne postoji.\n[Boskic] Draga moja, ako je sudjezik je zanimljiva, moram da priznajem, ali ja imam svoje iskustvene recepte, na primer rakije, ja ne nazivam rakijom, kuglicu, ona sama pokazuje da je rakija, ja uzmem dve treće čaše, ubacim dve tablete acetilsalicilne kiseline, malo šereta. Ako je zelena kuglica, onda više mogu da stavim šećera, ali ako je tamnoplava, tada ne treba previše, jer to često izaziva to snage vatrene ere i da kačeš obrazima.\n[Djordje Cvarkov] Ovo je najbolja varijanta koju je ikada izmislio ljudski rod. Ali mislim, stvarno, bez obzira na te male greške. Ma što toliko velike greške uzimate? Pa nije važno ko je, neki bi čak rekli niko. Ovako sada ide, samo kad uhvatimo, samo kad popijemo prve dve čaše, vrata mršima se otvaraju, izbacujemo sve ono loše, gore. Pa mi održavamo životno aktivnost nekih 20-30 godina. Pa bi se i 40 godina ove dreljesnice nisu držale. Dođe doktor, mislim gledaj, beba je samo bolesna. Mislim sranje. Zamarilo se nad glavom. A pogledaćete sve uređeno i perovi se raspominju. Savršeni, savršeni izlaz. Inače je orijentalni farmaceutski prir. Bazičnih metilenativacija ne smeštajte telo pri stalnim temperaturama između minus devet i plus dvadeset pet. To je savršeno mesto za čuvanje ovog sredstva. A najveći uticaj ima najviše drugih efekta ako se koristi u kombinaciji sa mentolom. Sada ja budem sprec ujutro kad ustanem, uzme čaj, metilu čaj, čak i ako me bole sandale, boljet nogu, boljet vrat, boljet kuk, boljet kičmu. Sve se to sagoreće i odmetnuti ti se.\n[Dragan Torbica] Nešto ona što kaže, kakva ona cijelo, necegova sestra. On joj je stariji,"}

In [0]:
HOLDOUT_MAX_NEW_TOKENS = 1024
holdout_rows = split_rows["test"]
if not holdout_rows:
    raise RuntimeError("No holdout episodes found")

client = MlflowClient()

for index, heldout in enumerate(holdout_rows, start=1):
    episode_key = heldout["episode_key"]
    print(f"[{index}/{len(holdout_rows)}] generating episode {episode_key}")
    comparison = {
        "episode_key": episode_key,
        "holdout_index": index,
        "premise": heldout["premise"],
        "reference": heldout["completion"][0]["content"],
        "base": generate_episode(
            model,
            tokenizer,
            heldout["premise"],
            adapter_enabled=False,
            seed=SEED,
            max_new_tokens=HOLDOUT_MAX_NEW_TOKENS,
            do_sample=GENERATION_DO_SAMPLE,
            temperature=GENERATION_TEMPERATURE,
            top_p=GENERATION_TOP_P,
            top_k=GENERATION_TOP_K,
            repetition_penalty=GENERATION_REPETITION_PENALTY,
        ),
        "qlora": generate_episode(
            model,
            tokenizer,
            heldout["premise"],
            adapter_enabled=True,
            seed=SEED,
            max_new_tokens=HOLDOUT_MAX_NEW_TOKENS,
            do_sample=GENERATION_DO_SAMPLE,
            temperature=GENERATION_TEMPERATURE,
            top_p=GENERATION_TOP_P,
            top_k=GENERATION_TOP_K,
            repetition_penalty=GENERATION_REPETITION_PENALTY,
        ),
        "generation_config": {
            "seed": SEED,
            "max_new_tokens": HOLDOUT_MAX_NEW_TOKENS,
            "do_sample": GENERATION_DO_SAMPLE,
            "temperature": GENERATION_TEMPERATURE,
            "top_p": GENERATION_TOP_P,
            "top_k": GENERATION_TOP_K,
            "repetition_penalty": GENERATION_REPETITION_PENALTY,
        },
    }
    artifact_path = f"heldout-comparisons/episode-{index:03d}.json"
    client.log_dict(TRAINING_RUN_ID, comparison, artifact_path)
    print(f"saved {artifact_path}")

print(
    f"Saved {len(holdout_rows)} comparisons under "
    f"runs:/{TRAINING_RUN_ID}/heldout-comparisons/"
)